version: '3'
services:
  app:
    image: jheffh2012/cluster-front:1.0.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

#Volumes
volumes:
  dbdata:
    driver: local
